### ISSUE TITLE
Installation on CentOS 7

### ISSUE THREAD

**Issue by andrein** [wglass/collectd-haproxy#1]
Hello,

I'm trying to install the plugin, but I get the following error on CentOS7 (Python 2.7.5, collectd 5.5.0):

```
[root@haproxy1 ~]# pip install collectd-haproxy
You are using pip version 7.1.0, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting collectd-haproxy
  Using cached collectd-haproxy-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-n28EWt/collectd-haproxy/setup.py", line 3, in <module>
        from collectd_haproxy import __version__
      File "collectd_haproxy/__init__.py", line 15, in <module>
        HAProxyPlugin.register(collectd)
      File "collectd_haproxy/plugin.py", line 54, in register
        collectd.register_config(instance.configure, name=cls.name)
    AttributeError: 'module' object has no attribute 'register_config'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-n28EWt/collectd-haproxy
```

Thanks,
Andrei

**Comment by wglass** [comment]
Hrm, interesting.  So you have a "collectd" module but that module doesn't have "register_config" function like it should:

https://collectd.org/documentation/manpages/collectd-python.5.shtml#register_config

Do you happen to have this other module named "collectd" installed?

https://pypi.python.org/pypi/collectd/

I was able to recreate your error locally by installing that first. I'll update the **init**.py file to be a 
little smarter about which collectd module it finds and see if that does the trick.

I get the feeling that sort of setup might still have trouble running python collectd plugins once they're installed.  Once collectd spins up a python process and the plugin starts you're liable to run into the same
error.  if that happens you can:

1) remove that second "collectd" module if you're not using it
2) isolate the modules with virutalenvs so they don't conflict with each other.

**Comment by andrein** [comment]
Hello William,

Thank you for the quick reply, you were right, It seems I did have the (wrong) collectd module installed.

I've removed it and the plugin installed without a hitch.

Thanks,
Andrei
