### ISSUE TITLE
Run on python2.6

### ISSUE THREAD

**Issue by ferztyle** [wglass/collectd-haproxy#17]
Hi, is there a way to run on python 2.6.6? I have a production server and can't update the python version.
Thanks!

**Comment by wglass** [comment]
I've added python 2.6 to the tox test suite so it _should_ already work, but I've never used it on 2.6 directly myself. Are you getting an error when you try to use it?

**Comment by ferztyle** [comment]
Hi!, I have installed without any errors, it only was a problem with permissions. It works very well with python2.6. Thanks for your help!
